pluginManagement {
    if (System.getProperty("profile") == "local") {
        println "Local dev plugin"
        includeBuild '../openapi-jaxrs-client'
    } else if (System.getProperty("profile") == "local-snapshot") {
        println "Local SNAPSHOT plugin"
        repositories {
          mavenCentral()
          gradlePluginPortal()
          mavenLocal()
       }
    } else {
        println "Official built plugin"
    }
}